### PR TITLE
Enhanced RDoc for Document

### PR DESCRIPTION
**Pull request by BurdetteLamar**
Revises prefatory material, and methods:
- new
- node_type
- clone
- expanded_name
- add

Note well:  When I run this through rdoc, the call-seq for method expanded_name, and its aliased method name, does not show up.  I have no theory that explains that.

### CODE REVIEW

**Comment by BurdetteLamar** [comment]
@kou, did you see this one?  I left it as a draft b/c it has a problem with a call-seq.

**Comment by kou** [comment]
It seems that the `expanded_name` and `name` problem is a bug of RDoc. Could you report it to RDoc?
It seems that the `name` method name may be related.

**Comment by BurdetteLamar** [comment]
A workaround for the rdoc bug is to omit the call-seq for expanded_name, which is now done here.

I'll have to study how to correctly submit a bug for RDoc.

**Comment by BurdetteLamar** [comment]
@kou, now ready for review.

**Comment by BurdetteLamar** [comment]
@kou said:

> 
> 
> It seems that the `expanded_name` and `name` problem is a bug of RDoc. Could you report it to RDoc?
> It seems that the `name` method name may be related.

https://github.com/ruby/rdoc/issues/792

**Comment by BurdetteLamar** [comment]
Restored the call-seq for Document#expanded_name.

**Comment by kou** [comment]
Thanks!

**Pull request merged**
