### PR TITLE
Adding method Elements#parent

### PR DESCRIPTION
**Pull request by BurdetteLamar**
This is mainly to establish the concept of _base_ _element_, and to be able to retrieve the element elsewhere in the example code.

Next, I'll modify one or two remarks in the existing doc for Elements, then proceed with more RDoc for the class.

### CODE REVIEW

**Comment by BurdetteLamar** [comment]
@kou, I have fouled up these PRs.  I thought the earlier one was already merged.  Let me know if you want these closed and re-pushed cleanly.

**Comment by kou** [comment]
`Elements#parent` is better for consistency.
We have `Child#parent`.

**Comment by BurdetteLamar** [comment]
> 
> 
> `Elements#parent` is better for consistency.
> We have `Child#parent`.

Fixed.

**Comment by kou** [comment]
Could you also update document?

**Comment by BurdetteLamar** [comment]
> 
> 
> Could you also update document?

Done.

**Comment by BurdetteLamar** [comment]
@kou, I think I have this cleaned up now.

**Comment by kou** [comment]
Thanks!

**Pull request merged**
